<x-user-components.layout>
    <x-user-components.banner></x-user-components.banner>
    <x-user-components.men-section></x-user-components.men-section>
    <x-user-components.women-section></x-user-components.women-section>
    <x-user-components.kids-section></x-user-components.kids-section>
    <x-user-components.accessories-section></x-user-components.accessories-section>
    <x-user-components.explore></x-user-components.explore>
    <x-user-components.footer></x-user-components.footer>
</x-user-components.layout>
